# This is a basic workflow that is manually triggered
name: Call Caprover Build

# Controls when the action will run. Workflow runs when manually triggered using the UI or API.
on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches: [publish-caprover]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  caprover_webhook_call:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Webhook
        uses: distributhor/workflow-webhook@v3
        env:
          webhook_url: "https://captain.int2.lv-aws-x3.xyzapps.xyz/api/v2/user/apps/webhooks/triggerbuild?namespace=captain&token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7InRva2VuVmVyc2lvbiI6IjVjNmI3ZmI0LTU3YzEtNDRmMi05MjZlLWQ0MmQ3MDI3ZDU1OSIsImFwcE5hbWUiOiJ2aXJ0dWFsaHEtbW9iaWxlIiwibmFtZXNwYWNlIjoiY2FwdGFpbiJ9LCJpYXQiOjE3MTE1MTE3MTl9.f1p5WxOkcEvhFlDlJO9SuMADuhTz0TlBaZ1IT3JzN-8"
